services:
  - type: web
    name: commanding-liberty
    runtime: docker
    rootDir: cle
    plan: free
    healthCheckPath: /health.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
